version: '3.1'

services:
  jrtb-db:
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'Deador'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'DeadorAndrii'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'DeadorAndrii'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3308 on the container
      - '3308'